apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../base]
patches: [{path: platform-patch.yaml}]
images:
- {name: ghcr.io/fourtytwo42/keelmesh, newName: ACCOUNT.dkr.ecr.REGION.amazonaws.com/keelmesh, newTag: release-sha}
- {name: ghcr.io/fourtytwo42/keelmesh-ai, newName: ACCOUNT.dkr.ecr.REGION.amazonaws.com/keelmesh-ai, newTag: release-sha}
