import { useState } from "react";
import { api, requestID } from "./api";
import type { AgentSessionV1, ArenaSnapshotV1, EngagementLeaseV1, EngagementPlanV1 } from "./types";

type Props={value:ArenaSnapshotV1;onChange:(v:ArenaSnapshotV1)=>void;onError:(v:string)=>void};
const mutation=(value:ArenaSnapshotV1,kind:string)=>({request_id:requestID(kind),idempotency_key:requestID(`${kind}-key`),expected_version:value.state_version,actor_id:value.viewer_faction});

export function ArenaView({value,onChange,onError}:Props){
 const[busy,setBusy]=useState(false),[text,setText]=useState("Frame my fleet, open radar contacts, and mark the uncertain track"),[session,setSession]=useState<AgentSessionV1|null>(null),[plan,setPlan]=useState<EngagementPlanV1|null>(null),[lease,setLease]=useState<EngagementLeaseV1|null>(null),[effect,setEffect]=useState("");
 const coord=value.coordinators[0];
 async function run<T>(fn:()=>Promise<T>){setBusy(true);onError("");try{return await fn()}catch(e){onError(String(e));return null}finally{setBusy(false)}}
 async function command(path:string,body:Record<string,unknown>){const next=await run(()=>api<ArenaSnapshotV1>(path,{method:"POST",body:JSON.stringify({...mutation(value,path),...body})}));if(next)onChange(next)}
 async function ask(){let current=session;if(!current){current=await run(()=>api<AgentSessionV1>("/api/v3/agent/sessions",{method:"POST",body:JSON.stringify({...mutation(value,"agent-session"),faction:value.viewer_faction,text:""})}))??null;if(!current)return;setSession(current);onChange(await api(`/api/v3/arena?faction=${value.viewer_faction}`))}const fresh=await api<ArenaSnapshotV1>(`/api/v3/arena?faction=${value.viewer_faction}`);const answer=await run(()=>api<AgentSessionV1>(`/api/v3/agent/sessions/${current.id}/messages`,{method:"POST",body:JSON.stringify({...mutation(fresh,"agent-message"),faction:value.viewer_faction,text})}));if(answer){setSession(answer);onChange(await api(`/api/v3/arena?faction=${value.viewer_faction}`))}}
 async function planEffect(){const fresh=await api<ArenaSnapshotV1>(`/api/v3/arena?faction=${value.viewer_faction}`);const p=await run(()=>api<EngagementPlanV1>(`/api/v3/matches/${fresh.match_id}/engagements:plan`,{method:"POST",body:JSON.stringify({...mutation(fresh,"engagement-plan"),faction:fresh.viewer_faction,friendly_node_ids:[fresh.nodes[4].id],target_track_ids:[fresh.knowledge.contacts[0].id],equipment:["light_kinetic"],maximum_effects:1})}));if(p){setPlan(p);onChange(await api(`/api/v3/arena?faction=${value.viewer_faction}`))}}
 async function authorize(){if(!plan)return;const fresh=await api<ArenaSnapshotV1>(`/api/v3/arena?faction=${value.viewer_faction}`);const l=await run(()=>api<EngagementLeaseV1>(`/api/v3/matches/${fresh.match_id}/engagements/${plan.id}:authorize`,{method:"POST",body:JSON.stringify({...mutation(fresh,"engagement-authorize"),plan_hash:plan.content_hash,operator_id:`demo-player-${value.viewer_faction.toLowerCase()}`})}));if(l){setLease(l);onChange(await api(`/api/v3/arena?faction=${value.viewer_faction}`))}}
 async function apply(){if(!lease||!plan)return;const fresh=await api<ArenaSnapshotV1>(`/api/v3/arena?faction=${value.viewer_faction}`);const e=await run(()=>api<{outcome:string}>(`/api/v3/matches/${fresh.match_id}/effects`,{method:"POST",body:JSON.stringify({...mutation(fresh,"arena-effect"),lease_id:lease.id,target_track_id:plan.target_track_ids[0],equipment:plan.equipment[0]})}));if(e){setEffect(e.outcome);onChange(await api(`/api/v3/arena?faction=${value.viewer_faction}`))}}
 return <div className="arena-view">
  <div className="arena-identity"><b>PLAYER {value.viewer_faction}</b><span>COORDINATOR {coord.node_id.toUpperCase()}</span><span>VM {value.nodes.find(n=>n.id===coord.node_id)?.planned_vm_id}</span><span>EPOCH {coord.epoch}</span><span>{coord.votes}/6 NODES</span><em>{value.simulation_rate}× SIM</em></div>
  <div className="arena-grid"><section><header><span>SYMMETRIC NODE FABRIC</span><b>{value.provisioning_state.replaceAll("_"," ")}</b></header><div className="arena-nodes">{value.nodes.map(n=><article key={n.id} className={n.role}><div><b>{n.id.toUpperCase()}</b><small>{n.class} · VM {n.planned_vm_id} · {n.host}</small></div><span>{n.role}</span><dl><i>MGMT<strong>{n.management_connected?"UP":"DOWN"}</strong></i><i>AI<strong>{n.inference_connected?"UP":"DOWN"}</strong></i><i>RADIO<strong>{n.radio_state}</strong></i><i>ENERGY<strong>{Math.round(n.battery_kwh/n.battery_capacity_kwh*100)}%</strong></i></dl></article>)}</div></section>
  <aside><div className="arena-planes"><label>MANAGEMENT <b>{value.management_plane}</b></label><label>INFERENCE <b>{value.inference_plane}</b></label><label>MISSION RADIO <b>{value.radio_plane}</b></label></div><h3>KNOWLEDGE-LIMITED CONTACTS</h3>{value.knowledge.contacts.map(t=><article className="contact-card" key={t.id}><b>{t.classification}</b><span>{Math.round(t.confidence*100)}% confidence · ±{t.uncertainty_m}m</span><small>{t.source} · hostility {t.hostility}</small></article>)}<div className="arena-controls"><button disabled={busy||value.phase!=="lobby"} onClick={()=>command("/api/v3/matches",{})}>START MATCH</button><button disabled={busy} onClick={()=>command(`/api/v3/matches/${value.match_id}/faults`,{faction:value.viewer_faction,kind:"fail_starlink"})}>FAIL STARLINK</button><button disabled={busy} onClick={()=>command(`/api/v3/matches/${value.match_id}/faults`,{faction:value.viewer_faction,kind:"partition_coordinator"})}>ISOLATE COORDINATOR</button><button disabled={busy} onClick={()=>command(`/api/v3/matches/${value.match_id}/faults`,{faction:value.viewer_faction,kind:"restore_radio"})}>RESTORE RADIO</button><button disabled={busy} onClick={()=>command(`/api/v3/matches/${value.match_id}/advance`,{seconds:600})}>+10 SIM MIN</button></div></aside></div>
  <div className="arena-agent"><label>NODE AGENT · SEMANTIC WORKSPACE TOOLS<input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}}/></label><button onClick={ask} disabled={busy}>ASK MORGAN</button>{session&&<p>{session.message}<small>{(session.actions??[]).map(a=>a.kind).join(" → ")}</small></p>}</div>
  <div className="engagement-flow"><div><small>BOUNDED FICTIONAL EFFECT</small><b>{effect||plan?.summary||"No effect proposal"}</b>{plan&&<code>{plan.content_hash.slice(0,32)}…</code>}</div>{!plan?<button onClick={planEffect}>DRAFT ENGAGEMENT</button>:!lease?<button className="danger" onClick={authorize}>CONFIRM EXACT HASH</button>:!effect?<button className="danger" onClick={apply}>APPLY 1 SIMULATED EFFECT</button>:<span className="receipt">IMMUTABLE RECEIPT</span>}</div>
  <div className="arena-events">{value.events.slice(-5).reverse().map(e=><span key={e.sequence}><time>T+{e.tick}</time><b>{e.kind}</b>{e.summary}</span>)}</div>
 </div>
}
