import { useEffect, useRef, useState } from "react";
import * as maplibregl from "maplibre-gl";
import type { GeoJSONSource, Map as MLMap, MapMouseEvent, StyleSpecification } from "maplibre-gl";
import maplibreWorkerURL from "maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url";
import "maplibre-gl/dist/maplibre-gl.css";
import type { FleetPlanV2, FleetSnapshotV2, MissionWorkspaceV2, Point } from "./types";

maplibregl.setWorkerUrl(maplibreWorkerURL);
type Tool="select"|"box"|"waypoint"|"include"|"exclude";
type Props={fleet:FleetSnapshotV2;mission:MissionWorkspaceV2|null;selected:Set<string>;activePlan:FleetPlanV2|null;tool:Tool;pirate:boolean;onSelect:(ids:string[],mode:"replace"|"toggle")=>void;onGroup:(id:string)=>void;onWaypoint:(p:Point)=>void;onArea:(kind:"include"|"exclude",polygon:Point[])=>void;onToolDone:()=>void};
const empty:GeoJSON.FeatureCollection={type:"FeatureCollection",features:[]};
const style:StyleSpecification={version:8,sources:{coast:{type:"geojson",data:"/assets/maps/narragansett.geojson"}},layers:[
  {id:"sea",type:"background",paint:{"background-color":"#0b2731"}},
  {id:"bathymetry",type:"background",paint:{"background-color":"#12333d","background-opacity":.78}},
  {id:"shipping",type:"line",source:"coast",filter:["==",["get","kind"],"shipping"],paint:{"line-color":"#9f8b55","line-width":1,"line-dasharray":[3,4],"line-opacity":.55}},
  {id:"labels",type:"symbol",source:"coast",filter:["==",["get","kind"],"label"],layout:{"text-field":["get","name"],"text-size":11,"text-letter-spacing":.08},paint:{"text-color":"#b9b5a8","text-halo-color":"#151c1d","text-halo-width":1.5}}
]};

function vesselData(fleet:FleetSnapshotV2):GeoJSON.FeatureCollection{return{type:"FeatureCollection",features:fleet.vessels.map(v=>({type:"Feature",id:v.id,properties:{id:v.id,name:v.callsign,designation:v.designation,group:v.group_id,groupCode:v.group_code,color:v.group_color,class:v.class.id,heading:v.telemetry.heading_deg,reserve:Math.round(v.telemetry.reserve*100),mode:v.telemetry.mode},geometry:{type:"Point",coordinates:v.telemetry.position}}))}}
function routeData(plan:FleetPlanV2|null):GeoJSON.FeatureCollection{return{type:"FeatureCollection",features:plan?.assignments.map(a=>({type:"Feature",properties:{vessel:a.vessel_id},geometry:{type:"LineString",coordinates:a.route}}))??[]}}
function geometryData(mission:MissionWorkspaceV2|null):GeoJSON.FeatureCollection{return{type:"FeatureCollection",features:[...(mission?.geometry.included_areas??[]).map((coordinates,index)=>({type:"Feature" as const,properties:{kind:"include",index},geometry:{type:"Polygon" as const,coordinates:[coordinates]}})),...(mission?.geometry.exclusion_areas??[]).map((coordinates,index)=>({type:"Feature" as const,properties:{kind:"exclude",index},geometry:{type:"Polygon" as const,coordinates:[coordinates]}})),...(mission?.geometry.waypoints??[]).map((coordinates,index)=>({type:"Feature" as const,properties:{kind:"waypoint",index:index+1},geometry:{type:"Point" as const,coordinates}}))]}}

export function OperationsMap({fleet,mission,selected,activePlan,tool,pirate,onSelect,onGroup,onWaypoint,onArea,onToolDone}:Props){
 const host=useRef<HTMLDivElement>(null),mapRef=useRef<MLMap|null>(null),boxStart=useRef<{x:number;y:number}|null>(null),selectionMode=useRef(false);const[ready,setReady]=useState(false),[box,setBox]=useState<{x:number;y:number;w:number;h:number}|null>(null);
 useEffect(()=>{if(!host.current||mapRef.current)return;const map=new maplibregl.Map({container:host.current,style,center:[-71.34,41.35],zoom:9.1,pitch:24,bearing:-8,maxPitch:60,minZoom:7,maxZoom:16,attributionControl:false,maxBounds:[[-72.1,40.75],[-70.55,42.05]]});map.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true,visualizePitch:true}),"bottom-right");map.addControl(new maplibregl.ScaleControl({unit:"nautical"}),"bottom-left");mapRef.current=map;map.on("load",async()=>{
   for(const name of ["kestrel","mariner","atlas"]){const image=await map.loadImage(`/assets/vessels/${name}.png`);map.addImage(`vessel-${name}`,image.data,{pixelRatio:8})}
   map.addSource("mission-geometry",{type:"geojson",data:empty});map.addLayer({id:"mission-areas",type:"fill",source:"mission-geometry",filter:["in",["get","kind"],["literal",["include","exclude"]]],paint:{"fill-color":["match",["get","kind"],"exclude","#d06054","#d6a242"],"fill-opacity":.13}});map.addLayer({id:"mission-area-lines",type:"line",source:"mission-geometry",filter:["in",["get","kind"],["literal",["include","exclude"]]],paint:{"line-color":["match",["get","kind"],"exclude","#e26e62","#e6a63b"],"line-width":2,"line-dasharray":[3,2]}});map.addLayer({id:"mission-waypoints",type:"circle",source:"mission-geometry",filter:["==",["get","kind"],"waypoint"],paint:{"circle-color":"#e6a63b","circle-radius":7,"circle-stroke-color":"#171b1b","circle-stroke-width":2}});
   map.addSource("routes",{type:"geojson",data:empty});map.addLayer({id:"mission-routes",type:"line",source:"routes",paint:{"line-color":"#e6a63b","line-width":2.5,"line-dasharray":[2,1.6],"line-opacity":.9}});
   map.addSource("vessels",{type:"geojson",data:vesselData(fleet),cluster:true,clusterRadius:46,clusterMaxZoom:8});
   map.addLayer({id:"clusters",type:"circle",source:"vessels",filter:["has","point_count"],paint:{"circle-color":"#d29a3e","circle-radius":["step",["get","point_count"],17,20,23,40,30],"circle-stroke-color":"#221d14","circle-stroke-width":3}});
   map.addLayer({id:"cluster-count",type:"symbol",source:"vessels",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":11},paint:{"text-color":"#17130d"}});
   map.addLayer({id:"group-halos",type:"circle",source:"vessels",filter:["!",["has","point_count"]],paint:{"circle-radius":["case",["boolean",["feature-state","selected"],false],19,14],"circle-color":"transparent","circle-stroke-color":["get","color"],"circle-stroke-width":["case",["boolean",["feature-state","selected"],false],4,2],"circle-opacity":.9}});
   map.addLayer({id:"vessel-symbols",type:"symbol",source:"vessels",filter:["!",["has","point_count"]],layout:{"icon-image":["concat","vessel-",["get","class"]],"icon-size":["interpolate",["linear"],["zoom"],8,.13,11,.22,15,.34],"icon-rotate":["get","heading"],"icon-rotation-alignment":"map","icon-allow-overlap":true,"text-field":["step",["zoom"],"",10,["concat",["get","name"]," · ",["get","groupCode"]]],"text-size":10,"text-offset":[0,2.2],"text-allow-overlap":false},paint:{"text-color":"#ece8dc","text-halo-color":"#111718","text-halo-width":2}});
   map.addLayer({id:"reserve-badges",type:"symbol",source:"vessels",filter:["!",["has","point_count"]],minzoom:12,layout:{"text-field":["concat",["to-string",["get","reserve"]],"%"],"text-size":8,"text-offset":[0,-2.2]},paint:{"text-color":"#efe7d4","text-halo-color":"#161d1e","text-halo-width":2}});setReady(true)
 });return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{if(!ready||!mapRef.current)return;(mapRef.current.getSource("vessels")as GeoJSONSource)?.setData(vesselData(fleet));(mapRef.current.getSource("routes")as GeoJSONSource)?.setData(routeData(activePlan));(mapRef.current.getSource("mission-geometry")as GeoJSONSource)?.setData(geometryData(mission))},[ready,fleet,activePlan,mission]);
 useEffect(()=>{const map=mapRef.current;if(!ready||!map)return;map.setPaintProperty("sea","background-color",pirate?"#071b1b":"#0b2731");map.setPaintProperty("bathymetry","background-color",pirate?"#102a27":"#12333d");map.setPaintProperty("shipping","line-color",pirate?"#d1aa58":"#9f8b55")},[ready,pirate]);
 useEffect(()=>{if(!ready||!mapRef.current)return;for(const v of fleet.vessels)mapRef.current.setFeatureState({source:"vessels",id:v.id},{selected:selected.has(v.id)})},[ready,selected,fleet.vessels]);
 useEffect(()=>{const map=mapRef.current;if(!ready||!map)return;const canvas=map.getCanvas();canvas.style.cursor=tool==="select"?"default":"crosshair";const click=(e:MapMouseEvent)=>{if(tool==="waypoint"){onWaypoint([e.lngLat.lng,e.lngLat.lat]);onToolDone();return}const hit=map.queryRenderedFeatures(e.point,{layers:["vessel-symbols","group-halos"]})[0];if(hit?.properties?.id)onSelect([hit.properties.id],e.originalEvent.shiftKey?"toggle":"replace")};const dbl=(e:MapMouseEvent)=>{const hit=map.queryRenderedFeatures(e.point,{layers:["vessel-symbols","group-halos"]})[0];if(hit?.properties?.group){e.preventDefault();onGroup(hit.properties.group)}};const down=(e:MapMouseEvent)=>{if(!["box","include","exclude"].includes(tool)&&!e.originalEvent.shiftKey)return;selectionMode.current=true;boxStart.current={x:e.point.x,y:e.point.y};map.dragPan.disable();setBox({x:e.point.x,y:e.point.y,w:0,h:0})};const move=(e:MapMouseEvent)=>{if(!selectionMode.current||!boxStart.current)return;const s=boxStart.current;setBox({x:Math.min(s.x,e.point.x),y:Math.min(s.y,e.point.y),w:Math.abs(e.point.x-s.x),h:Math.abs(e.point.y-s.y)})};const up=(e:MapMouseEvent)=>{if(!selectionMode.current||!boxStart.current)return;const s=boxStart.current;const min={x:Math.min(s.x,e.point.x),y:Math.min(s.y,e.point.y)},max={x:Math.max(s.x,e.point.x),y:Math.max(s.y,e.point.y)};if(tool==="include"||tool==="exclude"){const nw=map.unproject([min.x,min.y]),se=map.unproject([max.x,max.y]);onArea(tool,[[nw.lng,nw.lat],[se.lng,nw.lat],[se.lng,se.lat],[nw.lng,se.lat],[nw.lng,nw.lat]])}else{const hits=map.queryRenderedFeatures([[min.x,min.y],[max.x,max.y]],{layers:["vessel-symbols","group-halos"]});onSelect([...new Set(hits.map(h=>String(h.properties?.id)).filter(Boolean))],e.originalEvent.shiftKey?"toggle":"replace")};selectionMode.current=false;boxStart.current=null;map.dragPan.enable();setBox(null);onToolDone()};map.on("click",click);map.on("dblclick",dbl);map.on("mousedown",down);map.on("mousemove",move);map.on("mouseup",up);return()=>{map.off("click",click);map.off("dblclick",dbl);map.off("mousedown",down);map.off("mousemove",move);map.off("mouseup",up)}},[ready,tool,onSelect,onGroup,onWaypoint,onArea,onToolDone]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onSelect([],"replace")};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[onSelect]);
 return <div className="operations-map" ref={host}>{box&&<div className="selection-box" style={{left:box.x,top:box.y,width:box.w,height:box.h}}/>}<div className="map-fixture-label"><strong>{pirate?"CHARTED WATERS · SIMULATION":"SIMULATION ONLY"}</strong><span>{pirate?"Local vector sea chart · not for navigation":"Local vector basemap · not for navigation"}</span></div></div>
}
