import { useState } from "react";
import { api, requestID } from "./api";
import type { FleetSnapshot, LoadRun, PlatformSnapshot, QuarantineRecord, ReplayRun } from "./types";

type Props={value:PlatformSnapshot;fleet:FleetSnapshot;onError:(v:string)=>void};
const n=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(value);
const ms=(value:number)=>`${value.toFixed(value<100?1:0)} ms`;

export function PlatformCutaway({value,fleet,onError}:Props){
 const [busy,setBusy]=useState(""); const [replay,setReplay]=useState<ReplayRun|null>(null);
 async function mutate<T>(label:string,path:string,body:Record<string,unknown>){setBusy(label);onError("");try{return await api<T>(path,{method:"POST",body:JSON.stringify({request_id:requestID(label),idempotency_key:requestID(label),expected_platform_state_version:value.state_version,...body})})}catch(e){onError(e instanceof Error?e.message:String(e));throw e}finally{setBusy("")}}
 async function start(){await mutate("load","/api/v1/load/runs",{profile:"interview",seed:424242})}
 async function stop(){if(value.active_run)await mutate("stop",`/api/v1/load/runs/${value.active_run.id}:stop`,{})}
 async function terminate(){await mutate("fault","/api/v1/platform/faults",{kind:"terminate_worker",target_id:"worker-2"})}
 async function redrive(item:QuarantineRecord){await mutate("redrive",`/api/v1/quarantine/${item.id}:redrive`,{})}
 async function runReplay(){if(!value.active_run)return;const result=await mutate<ReplayRun>("replay","/api/v1/platform/replays",{source_run_id:value.active_run.id});setReplay(result)}
 async function waitFor(predicate:(p:PlatformSnapshot)=>boolean,seconds:number){const deadline=Date.now()+seconds*1000;while(Date.now()<deadline){const p=await api<PlatformSnapshot>("/api/v1/platform");if(predicate(p))return p;await new Promise(r=>setTimeout(r,1000))}throw new Error("Timed out waiting for a measured drill milestone.")}
 async function autoRun(){setBusy("auto");onError("");try{let p=await api<PlatformSnapshot>("/api/v1/platform");let run:LoadRun|undefined=p.active_run;if(!run||run.state!=="running"){run=await api<LoadRun>("/api/v1/load/runs",{method:"POST",body:JSON.stringify({request_id:requestID("auto-load"),idempotency_key:requestID("auto-load"),expected_platform_state_version:p.state_version,profile:"interview",seed:424242})})}await new Promise(r=>setTimeout(r,10000));p=await api<PlatformSnapshot>("/api/v1/platform");const oldPID=p.workers.find(w=>w.id==="worker-2")?.pid;const lag=p.metrics.current_lag;await api("/api/v1/platform/faults",{method:"POST",body:JSON.stringify({request_id:requestID("auto-fault"),idempotency_key:requestID("auto-fault"),expected_platform_state_version:p.state_version,kind:"terminate_worker",target_id:"worker-2"})});await waitFor(s=>!s.workers.some(w=>w.id==="worker-2"&&w.state==="running"),25);p=await waitFor(s=>s.workers.some(w=>w.id==="worker-2"&&w.state==="running"&&w.pid!==oldPID)&&s.metrics.current_lag<=Math.max(100,lag),65);p=await waitFor(s=>s.metrics.attempted>=120000,65);await api(`/api/v1/load/runs/${run.id}:stop`,{method:"POST",body:JSON.stringify({request_id:requestID("auto-stop"),idempotency_key:requestID("auto-stop"),expected_platform_state_version:p.state_version})});p=await waitFor(s=>s.metrics.current_lag===0,30);const q=p.quarantine.find(item=>item.repair_state==="pending");if(q){await api(`/api/v1/quarantine/${q.id}:redrive`,{method:"POST",body:JSON.stringify({request_id:requestID("auto-redrive"),idempotency_key:requestID("auto-redrive"),expected_platform_state_version:p.state_version})});await new Promise(r=>setTimeout(r,1500));p=await api<PlatformSnapshot>("/api/v1/platform")}const result=await api<ReplayRun>("/api/v1/platform/replays",{method:"POST",body:JSON.stringify({request_id:requestID("auto-replay"),idempotency_key:requestID("auto-replay"),expected_platform_state_version:p.state_version,source_run_id:run.id})});setReplay(result)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy("")}}
 const m=value.metrics;const flowing=m.events_per_second>0;const currentReplay=replay??value.replay;
 return <section className="cutaway" aria-label="Live infrastructure cutaway">
  <div className="mission-strip"><span>LIVE MISSION CONTROL</span><strong>{fleet.mission.phase.replaceAll("_"," ")}</strong><span>{fleet.vessels.length} foreground vessels</span><span className="isolation">ISOLATED FROM SCALE PLANE</span><i>{value.available?"M1/M2 healthy":"M3 degraded safely"}</i></div>
  <div className="cutaway-head"><div><small>MEASURED SINGLE-VM SCALE LAB</small><h1>The system, peeled open</h1><p>Every pulse below is driven by Kafka, PostgreSQL, and real Linux processes—not a scripted animation.</p></div><div className="run-controls">{!value.active_run||value.active_run.state!=="running"?<button onClick={start} disabled={!!busy}>Start 1,000-vessel run</button>:<button className="stop" onClick={stop} disabled={!!busy}>Stop run</button>}<button onClick={terminate} disabled={!!busy||!value.workers.some(w=>w.id==="worker-2"&&w.state==="running")}>Terminate Worker 2</button><button onClick={autoRun} disabled={!!busy}>{busy==="auto"?"Running milestones…":"Run full drill"}</button></div></div>
  <div className="metric-ribbon"><Metric label="INGRESS" value={`${n(m.events_per_second)} ev/s`} note={`${(m.bytes_per_second/1048576).toFixed(1)} MiB total`}/><Metric label="END-TO-END P95" value={ms(m.latency_p95_ms)} note={`p99 ${ms(m.latency_p99_ms)}`}/><Metric label="KAFKA LAG" value={n(m.current_lag)} note={`peak ${n(m.peak_lag)}`}/><Metric label="LOGICAL INSERTS" value={n(m.unique_inserted)} note={`${n(m.duplicates_suppressed)} duplicates blocked`}/><Metric label="REBALANCES" value={n(m.rebalance_count)} note={`${value.workers.filter(w=>w.state==="running").length}/3 workers live`}/></div>
  <div className={`pipeline ${flowing?"flowing":""}`}>
   <Stage title="Synthetic fleet" kind="PRODUCER" status={value.active_run?.state??"idle"}><strong>{value.active_run?.vessel_count??0}</strong><span>logical vessels</span><small>seed {value.active_run?.seed??"—"}</small><div className="outbox"><i/>64 MiB durable outbox</div></Stage>
   <Flow label={`${n(m.events_per_second)} / SEC`}/>
   <Stage title="Kafka KRaft" kind="EVENT FABRIC" status={value.available?"healthy":"offline"}><strong>12</strong><span>telemetry partitions</span><div className="partition-grid">{Array.from({length:12},(_,i)=><i key={i} className={value.assignments.some(a=>a.partition===i)?"owned":""}>{i}</i>)}</div><small>30 min · 128 MiB / partition</small></Stage>
   <Flow label={`LAG ${n(m.current_lag)}`}/>
   <div className="workers-stage"><header><small>REAL CONSUMER GROUP</small><strong>3 supervised processes</strong></header>{["worker-1","worker-2","worker-3"].map(id=>{const w=value.workers.find(item=>item.id===id);return <article key={id} className={w?.state==="running"?"worker-live":"worker-down"}><div><b>{id}</b><em>{w?.state??"starting"}</em></div><span>PID {w?.pid??"—"}</span><span>{w?.assigned_partitions.join(", ")||"rebalancing"}</span><span>{n(w?.batch_rate??0)} ev/s</span><small>{((w?.rss_bytes??0)/1048576).toFixed(1)} MiB RSS · epoch {w?.rebalance_epoch??0}</small></article>})}</div>
   <Flow label={`${n(m.unique_inserted)} COMMITTED`}/>
   <Stage title="PostgreSQL + pgvector" kind="PROJECTION" status="healthy"><strong>{n(m.unique_inserted)}</strong><span>unique events</span><ul><li><b>{n(m.duplicates_suppressed)}</b> deduplicated</li><li><b>{n(m.out_of_order)}</b> out of order</li><li><b>{n(m.quarantined)}</b> quarantined</li></ul><small>monotonic vessel_latest</small></Stage>
  </div>
  <div className="evidence-row"><section><header><span>QUARANTINE + REPAIR</span><strong>{value.quarantine.length} recent</strong></header>{value.quarantine.slice(0,3).map(q=><button key={q.id} onClick={()=>redrive(q)} disabled={!!busy||q.repair_state!=="pending"}><code>{q.id}</code><span>{q.reason}</span><em>{q.repair_state==="pending"?"Repair + redrive":q.repair_state}</em></button>)}{!value.quarantine.length&&<p>Invalid checksums will appear here as durable evidence.</p>}</section><section><header><span>SHADOW REPLAY PROOF</span><button onClick={runReplay} disabled={!!busy||!value.active_run}>Rebuild projection</button></header>{currentReplay?<div className={currentReplay.matches?"match":"mismatch"}><strong>{currentReplay.matches?"LIVE = SHADOW":"CHECKSUM MISMATCH"}</strong><span>{n(currentReplay.live_count)} / {n(currentReplay.shadow_count)} vessels</span><code>{currentReplay.shadow_checksum.slice(0,20)}…</code></div>:<p>Replay reconstructs an isolated projection and compares counts plus SHA-256 checksums.</p>}</section><section><header><span>ACCOUNTING</span><strong>{n(m.attempted)} attempted</strong></header><div className="accounting"><span>Persisted <b>{n(m.unique_inserted)}</b></span><span>Duplicate <b>{n(m.duplicates_suppressed)}</b></span><span>Quarantine <b>{n(m.quarantined)}</b></span><span>Dropped <b className={m.dropped?"bad":"good"}>{n(m.dropped)}</b></span></div></section></div>
  <footer className="cutaway-foot"><span className={value.available?"healthy":"unhealthy"}/><strong>{value.summary}</strong><small>sample {new Date(value.sampled_at).toLocaleTimeString()} · actual state · VM 214</small></footer>
 </section>
}
function Stage({title,kind,status,children}:{title:string;kind:string;status:string;children:React.ReactNode}){return <article className="pipeline-stage"><header><small>{kind}</small><i className={status==="healthy"||status==="running"?"ok":""}>{status}</i></header><h2>{title}</h2>{children}</article>}
function Flow({label}:{label:string}){return <div className="flow"><span>{label}</span><div><i/><i/><i/></div></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div><small>{label}</small><strong>{value}</strong><span>{note}</span></div>}
